// server/config/mockStore.js
// Pre-seeded in-memory store for instant zero-config interview demonstration
// and environments where local mongod service is not yet running.

import bcrypt from 'bcryptjs';

const hash = (pwd) => bcrypt.hashSync(pwd, 10);

export const initialData = {
  users: [
    {
      _id: 'usr_admin_1',
      name: 'Shashank Nerkar',
      email: 'shashanknerkar21@gmail.com',
      password: hash('admin123'),
      role: 'admin',
      phone: '+91 9028267274',
      bio: 'Managing Director & Chief Operations Head, RoadDrive Driving Academy. Oversees RTO licensing partnerships and accredited instructor standards.',
      location: 'Nashik, Maharashtra',
      availableSlots: [],
      enrolledCourses: [],
      createdAt: new Date().toISOString(),
    },
    {
      _id: 'usr_admin_alias',
      name: 'Shashank Nerkar',
      email: 'admin@roaddrive.com',
      password: hash('admin123'),
      role: 'admin',
      phone: '+91 9028267274',
      bio: 'Managing Director & Chief Operations Head, RoadDrive Driving Academy.',
      location: 'Nashik, Maharashtra',
      availableSlots: [],
      enrolledCourses: [],
      createdAt: new Date().toISOString(),
    },
    {
      _id: 'usr_inst_1',
      name: 'Surya Dada',
      email: 'surya.instructor@roaddrive.com',
      password: hash('instructor123'),
      role: 'instructor',
      phone: '+91 9028267274',
      bio: 'Senior Driving Instructor with 8+ years experience specializing in Mumbai traffic, clutch control on flyovers, and advanced road safety.',
      experienceYears: 8,
      hourlyRate: 4,
      location: 'Mumbai, Maharashtra',
      availableSlots: [
        { _id: 'slot_1', date: '2026-09-22', time: '09:00 AM', isBooked: true },
        { _id: 'slot_2', date: '2026-09-22', time: '11:00 AM', isBooked: false },
        { _id: 'slot_3', date: '2026-09-23', time: '02:00 PM', isBooked: false },
        { _id: 'slot_4', date: '2026-09-24', time: '10:00 AM', isBooked: false },
        { _id: 'slot_5', date: '2026-09-25', time: '04:00 PM', isBooked: false },
      ],
      enrolledCourses: [],
      createdAt: new Date().toISOString(),
    },
    {
      _id: 'usr_inst_alias',
      name: 'Surya Dada',
      email: 'john.instructor@roaddrive.com',
      password: hash('instructor123'),
      role: 'instructor',
      phone: '+91 9028267274',
      bio: 'Senior Driving Instructor with 8+ years experience specializing in Mumbai traffic.',
      experienceYears: 8,
      hourlyRate: 4,
      location: 'Mumbai, Maharashtra',
      availableSlots: [
        { _id: 'slot_1b', date: '2026-09-22', time: '09:00 AM', isBooked: true },
        { _id: 'slot_2b', date: '2026-09-22', time: '11:00 AM', isBooked: false },
      ],
      enrolledCourses: [],
      createdAt: new Date().toISOString(),
    },
    {
      _id: 'usr_inst_2',
      name: 'Rahul Jadhav',
      email: 'rahul.instructor@roaddrive.com',
      password: hash('instructor123'),
      role: 'instructor',
      phone: '+91 9028267274',
      bio: 'Certified Driving Instructor with 5+ years experience teaching highway merging, roundabouts, and RTO track testing in Nashik.',
      experienceYears: 5,
      hourlyRate: 2,
      location: 'Nashik, Maharashtra',
      availableSlots: [
        { _id: 'slot_6', date: '2026-09-22', time: '10:00 AM', isBooked: false },
        { _id: 'slot_7', date: '2026-09-23', time: '01:00 PM', isBooked: false },
        { _id: 'slot_8', date: '2026-09-24', time: '03:00 PM', isBooked: false },
      ],
      enrolledCourses: [],
      createdAt: new Date().toISOString(),
    },
    {
      _id: 'usr_inst_3',
      name: 'Priya Deshmukh',
      email: 'priya.instructor@roaddrive.com',
      password: hash('instructor123'),
      role: 'instructor',
      phone: '+91 9028267274',
      bio: 'Patient driving instructor specializing in city traffic, parallel parking in tight spaces, and defensive driving techniques across Pune.',
      experienceYears: 6,
      hourlyRate: 5,
      location: 'Pune, Maharashtra',
      availableSlots: [
        { _id: 'slot_9', date: '2026-09-22', time: '08:00 AM', isBooked: false },
        { _id: 'slot_10', date: '2026-09-23', time: '11:00 AM', isBooked: false },
        { _id: 'slot_11', date: '2026-09-25', time: '02:00 PM', isBooked: false },
      ],
      enrolledCourses: [],
      createdAt: new Date().toISOString(),
    },
    {
      _id: 'usr_stud_1',
      name: 'Rohit Shinde',
      email: 'student@roaddrive.com',
      password: hash('student123'),
      role: 'student',
      phone: '+91 9028267274',
      bio: 'Student driver preparing for Maharashtra RTO permanent light motor vehicle (LMV) driving licence exam.',
      location: 'Mumbai, Maharashtra',
      availableSlots: [],
      enrolledCourses: [
        {
          course: 'crs_1',
          enrolledAt: new Date(Date.now() - 7 * 86400000).toISOString(),
          completedLessons: ['lsn_1_1', 'lsn_1_2'],
          paymentStatus: 'paid',
          paymentId: 'pay_sim_init_test',
        },
      ],
      createdAt: new Date().toISOString(),
    },
    {
      _id: 'usr_stud_2',
      name: 'Neha Patil',
      email: 'neha.patil@roaddrive.com',
      password: hash('student123'),
      role: 'student',
      phone: '+91 9028267274',
      bio: 'Learning defensive driving and parking techniques for Pune city commute.',
      location: 'Pune, Maharashtra',
      availableSlots: [],
      enrolledCourses: [],
      createdAt: new Date().toISOString(),
    },
    {
      _id: 'usr_stud_3',
      name: 'Amit Kulkarni',
      email: 'amit.kulkarni@roaddrive.com',
      password: hash('student123'),
      role: 'student',
      phone: '+91 9028267274',
      bio: 'Preparing for RTO driving test at Nashik RTO track.',
      location: 'Nashik, Maharashtra',
      availableSlots: [],
      enrolledCourses: [],
      createdAt: new Date().toISOString(),
    },
  ],

  courses: [
    {
      _id: 'crs_0',
      name: 'Road Signs & Traffic Rules Orientation',
      description: 'Essential free curriculum covering Indian traffic signs, mandatory hand signals, zebra crossings, and RTO road rules.',
      price: 0,
      duration: '1 Week (4 Hours)',
      level: 'Beginner',
      thumbnail: 'https://images.unsplash.com/photo-1572949645841-094f3a9c4c94?w=600&auto=format&fit=crop&q=80',
      createdAt: new Date().toISOString(),
    },
    {
      _id: 'crs_1',
      name: 'Beginner Driving Course',
      description: 'Comprehensive driving fundamentals covering cockpit drill, clutch biting point, gear shifting, U-turns, and safe stopping.',
      price: 1,
      duration: '4 Weeks (20 Hours)',
      level: 'Beginner',
      thumbnail: 'https://images.unsplash.com/photo-1449965408869-eaa3f722e40d?w=600&auto=format&fit=crop&q=80',
      createdAt: new Date().toISOString(),
    },
    {
      _id: 'crs_2',
      name: 'City Driving Course',
      description: 'Navigate heavy Indian traffic, bumper-to-bumper crawling, flyover merges, junction discipline, and pedestrian awareness.',
      price: 2,
      duration: '3 Weeks (15 Hours)',
      level: 'Intermediate',
      thumbnail: 'https://images.unsplash.com/photo-1502877338535-766e1452684a?w=600&auto=format&fit=crop&q=80',
      createdAt: new Date().toISOString(),
    },
    {
      _id: 'crs_3',
      name: 'Parking & Reverse Practice',
      description: 'Master parallel parking in tight spaces, 45-degree angle reverse bay parking, and reversing on gradients without rolling.',
      price: 3,
      duration: '1 Week (8 Hours)',
      level: 'Beginner',
      thumbnail: 'https://images.unsplash.com/photo-1549399542-7e3f8b79c341?w=600&auto=format&fit=crop&q=80',
      createdAt: new Date().toISOString(),
    },
    {
      _id: 'crs_4',
      name: 'Highway Driving Course',
      description: 'Expressway driving mastery, high-speed lane discipline, blind spot checks, 3-second rule, and night driving safety.',
      price: 4,
      duration: '2 Weeks (12 Hours)',
      level: 'Advanced',
      thumbnail: 'https://images.unsplash.com/photo-1519641471654-76ce0107ad1b?w=600&auto=format&fit=crop&q=80',
      createdAt: new Date().toISOString(),
    },
    {
      _id: 'crs_5',
      name: 'RTO Test Preparation',
      description: 'Dedicated preparation for the official RTO track test: H-track reverse, 8-track maneuvers, gradient start, and mock evaluation.',
      price: 5,
      duration: '1 Week (6 Hours)',
      level: 'Advanced',
      thumbnail: 'https://images.unsplash.com/photo-1568605117036-5fe5e7bab0b7?w=600&auto=format&fit=crop&q=80',
      createdAt: new Date().toISOString(),
    },
  ],

  lessons: [
    {
      _id: 'lsn_0_1',
      title: 'Mandatory Regulatory & Cautionary Road Signs (Stop, Give Way, Speed Limit)',
      description: 'Comprehensive walkthrough of mandatory circular signs, triangular warnings, and priority right-of-way markings.',
      course: 'crs_0',
      order: 1,
      createdAt: new Date().toISOString(),
    },
    {
      _id: 'lsn_0_2',
      title: 'Traffic Signals, Zebra Crossings & Junction Priority',
      description: 'Understanding zebra crossings, traffic signal cycles, amber lights, and free left-turn regulations.',
      course: 'crs_0',
      order: 2,
      createdAt: new Date().toISOString(),
    },
    {
      _id: 'lsn_1_1',
      title: 'Cockpit Drill & Vehicle Ergonomics (Seat, Mirror, Seatbelt)',
      description: 'Learn the DSSSM routine (Doors, Seat, Steering, Seatbelt, Mirrors) and understanding dashboard indicators.',
      course: 'crs_1',
      order: 1,
      createdAt: new Date().toISOString(),
    },
    {
      _id: 'lsn_1_2',
      title: 'Clutch Biting Point, Gear Shifting & Smooth Braking',
      description: 'Mastering clutch biting point, blind spot observations, and progressive braking without engine stall.',
      course: 'crs_1',
      order: 2,
      createdAt: new Date().toISOString(),
    },
    {
      _id: 'lsn_1_3',
      title: 'Steering Discipline & Lane Alignment',
      description: 'Pull-push steering method, proper hand positioning, and staying centered in urban lanes.',
      course: 'crs_1',
      order: 3,
      createdAt: new Date().toISOString(),
    },
    {
      _id: 'lsn_1_4',
      title: 'T-Junctions, Crossings & Mirror-Signal-Manoeuvre',
      description: 'MSPSL routine (Mirrors, Signal, Position, Speed, Look) at busy T-junctions and crossroads.',
      course: 'crs_1',
      order: 4,
      createdAt: new Date().toISOString(),
    },
    {
      _id: 'lsn_2_1',
      title: 'Navigating Heavy City Traffic & Stop-and-Go Crawling',
      description: 'Bumper-to-bumper traffic management, preventing rollback on inclines, and maintaining calm focus.',
      course: 'crs_2',
      order: 1,
      createdAt: new Date().toISOString(),
    },
    {
      _id: 'lsn_2_2',
      title: 'Roundabout Rules, Flyover Merges & Lane Etiquette',
      description: 'Flyover approaches, merging with fast traffic, and lane discipline through multi-lane roundabouts.',
      course: 'crs_2',
      order: 2,
      createdAt: new Date().toISOString(),
    },
    {
      _id: 'lsn_2_3',
      title: 'Hazard Perception & Pedestrian Awareness',
      description: 'Anticipating auto-rickshaws, two-wheelers, crossing pedestrians, and sudden road obstacles.',
      course: 'crs_2',
      order: 3,
      createdAt: new Date().toISOString(),
    },
    {
      _id: 'lsn_3_1',
      title: '45-Degree Angle Reverse Bay Parking',
      description: 'Clear reference point technique using rear quarter glass and side mirrors for perfect slot entry.',
      course: 'crs_3',
      order: 1,
      createdAt: new Date().toISOString(),
    },
    {
      _id: 'lsn_3_2',
      title: 'Parallel Parking Technique with Curb Alignment',
      description: 'Aligning with neighboring vehicles, full-lock reverse turn, and counter-steering within 6 inches of the curb.',
      course: 'crs_3',
      order: 2,
      createdAt: new Date().toISOString(),
    },
    {
      _id: 'lsn_3_3',
      title: 'Reversing on Slopes & Tight Alley Navigation',
      description: 'Using the handbrake and clutch balance to reverse uphill without rolling forward.',
      course: 'crs_3',
      order: 3,
      createdAt: new Date().toISOString(),
    },
    {
      _id: 'lsn_4_1',
      title: 'Expressway Acceleration Lane Entry & Safe Merging',
      description: 'Using acceleration lanes, blind spot shoulder checks, and matching expressway traffic speeds safely.',
      course: 'crs_4',
      order: 1,
      createdAt: new Date().toISOString(),
    },
    {
      _id: 'lsn_4_2',
      title: 'High-Speed Overtaking, Blind Spot Checks & 3-Second Rule',
      description: 'Safe overtaking protocol on expressways, mirror checks, maintaining 3-second buffer distance.',
      course: 'crs_4',
      order: 2,
      createdAt: new Date().toISOString(),
    },
    {
      _id: 'lsn_4_3',
      title: 'Adverse Weather & Night Highway Driving Precautions',
      description: 'Monsoon driving, aquaplaning prevention, low-beam headlight etiquette, and highway emergency stops.',
      course: 'crs_4',
      order: 3,
      createdAt: new Date().toISOString(),
    },
    {
      _id: 'lsn_5_1',
      title: 'RTO 8-Shape Track & H-Track Reverse Test Mastery',
      description: 'Mastering the 8-track turning radius without touching poles, and completing the H-track reverse maneuver.',
      course: 'crs_5',
      order: 1,
      createdAt: new Date().toISOString(),
    },
    {
      _id: 'lsn_5_2',
      title: 'Gradient / Slope Stop-and-Go without Rollback',
      description: 'The mandatory RTO slope test: stopping on the ramp and pulling away cleanly without rolling backward.',
      course: 'crs_5',
      order: 2,
      createdAt: new Date().toISOString(),
    },
    {
      _id: 'lsn_5_3',
      title: 'RTO Learner Licence Form 2 & Motor Vehicles Act Essentials',
      description: 'Understanding legal requirements, documents to carry, mandatory L-board rules, and examiner expectations.',
      course: 'crs_5',
      order: 3,
      createdAt: new Date().toISOString(),
    },
  ],

  bookings: [
    {
      _id: 'bkg_1',
      student: 'usr_stud_1',
      instructor: 'usr_inst_1',
      date: '2026-09-22',
      time: '09:00 AM',
      status: 'accepted',
      notes: 'City traffic navigation and clutch control on Mumbai flyovers.',
      createdAt: new Date(Date.now() - 2 * 86400000).toISOString(),
    },
    {
      _id: 'bkg_2',
      student: 'usr_stud_1',
      instructor: 'usr_inst_2',
      date: '2026-09-25',
      time: '11:00 AM',
      status: 'pending',
      notes: 'RTO 8-track turning and reverse bay parking practice in Nashik.',
      createdAt: new Date(Date.now() - 1 * 86400000).toISOString(),
    },
  ],

  reviews: [
    {
      _id: 'rev_1',
      student: 'usr_stud_1',
      instructor: 'usr_inst_1',
      rating: 5,
      comment: 'Surya Dada is an outstanding instructor. He explains clutch control in Mumbai traffic so calmly that all my initial fear vanished. Highly recommend!',
      createdAt: new Date(Date.now() - 3 * 86400000).toISOString(),
    },
    {
      _id: 'rev_2',
      student: 'usr_stud_2',
      instructor: 'usr_inst_3',
      rating: 5,
      comment: 'Priya maam made parallel parking and slope stops so simple with clear reference points in Pune city.',
      createdAt: new Date(Date.now() - 2 * 86400000).toISOString(),
    },
    {
      _id: 'rev_3',
      student: 'usr_stud_3',
      instructor: 'usr_inst_2',
      rating: 5,
      comment: 'Cleared my RTO driving test on the first attempt in Nashik thanks to Rahul sirs rigorous track preparation!',
      createdAt: new Date(Date.now() - 1 * 86400000).toISOString(),
    },
  ],
};

// Mutable memory store
export const memoryDb = JSON.parse(JSON.stringify(initialData));

export const generateId = (prefix = 'id') => `${prefix}_${Date.now()}_${Math.random().toString(36).substr(2, 6)}`;

